"""updated biodiesel plants and added petroleum pipelines; normalized infrastructure address columns

Revision ID: 0006
Revises: 0005
Create Date: 2026-04-09 09:35:52.160720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infrastructure_biodiesel_plants', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_biodiesel_plants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('infrastructure_biodiesel_plants', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='address::integer')
    op.create_table('infrastructure_petroleum_pipelines',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('artificial', sa.Integer(), nullable=True),
    sa.Column('master_oid', sa.Integer(), nullable=True),
    sa.Column('commodity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('capacity', sa.Numeric(), nullable=True),
    sa.Column('vcr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shape_length', sa.Numeric(), nullable=True),
    sa.Column('mode_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('length', sa.Numeric(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry("MULTILINESTRING"), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('object_id'),
    )
    op.create_table('multilinestring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.Column('geoid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(spatial_index=False), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###

    # -------------------------------------------------------------------------
    # Infrastructure address normalization:
    # Drop raw address string columns, add address_id FK + timestamps
    # to all infrastructure tables that lacked them.
    # -------------------------------------------------------------------------

    # -- infrastructure_biosolids_facilities --
    op.drop_column('infrastructure_biosolids_facilities', 'facility_address')
    op.drop_column('infrastructure_biosolids_facilities', 'facility_city')
    op.drop_column('infrastructure_biosolids_facilities', 'state')
    op.drop_column('infrastructure_biosolids_facilities', 'facility_zip')
    op.drop_column('infrastructure_biosolids_facilities', 'facility_county')
    op.drop_column('infrastructure_biosolids_facilities', 'mailing_street_1')
    op.drop_column('infrastructure_biosolids_facilities', 'mailing_city')
    op.drop_column('infrastructure_biosolids_facilities', 'mailing_state')
    op.drop_column('infrastructure_biosolids_facilities', 'mailing_zip')
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_cafo_manure_locations --
    op.drop_column('infrastructure_cafo_manure_locations', 'address')
    op.drop_column('infrastructure_cafo_manure_locations', 'town')
    op.drop_column('infrastructure_cafo_manure_locations', 'state')
    op.drop_column('infrastructure_cafo_manure_locations', 'zip')
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_combustion_plants --
    op.drop_column('infrastructure_combustion_plants', 'city')
    op.drop_column('infrastructure_combustion_plants', 'county')
    op.add_column('infrastructure_combustion_plants',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_combustion_plants',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_combustion_plants',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_district_energy_systems --
    op.drop_column('infrastructure_district_energy_systems', 'city')
    op.drop_column('infrastructure_district_energy_systems', 'state')
    op.add_column('infrastructure_district_energy_systems',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_district_energy_systems',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_district_energy_systems',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_ethanol_biorefineries --
    op.drop_column('infrastructure_ethanol_biorefineries', 'address')
    op.drop_column('infrastructure_ethanol_biorefineries', 'city')
    op.drop_column('infrastructure_ethanol_biorefineries', 'state')
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_food_processing_facilities --
    op.drop_column('infrastructure_food_processing_facilities', 'address')
    op.drop_column('infrastructure_food_processing_facilities', 'county')
    op.drop_column('infrastructure_food_processing_facilities', 'city')
    op.drop_column('infrastructure_food_processing_facilities', 'state')
    op.drop_column('infrastructure_food_processing_facilities', 'zip')
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_landfills --
    op.drop_column('infrastructure_landfills', 'physical_address')
    op.drop_column('infrastructure_landfills', 'city')
    op.drop_column('infrastructure_landfills', 'county')
    op.drop_column('infrastructure_landfills', 'state')
    op.drop_column('infrastructure_landfills', 'zip_code')
    op.add_column('infrastructure_landfills',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_livestock_anaerobic_digesters --
    op.drop_column('infrastructure_livestock_anaerobic_digesters', 'city')
    op.drop_column('infrastructure_livestock_anaerobic_digesters', 'state')
    op.add_column('infrastructure_livestock_anaerobic_digesters',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_livestock_anaerobic_digesters',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_livestock_anaerobic_digesters',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_msw_to_energy_anaerobic_digesters --
    op.drop_column('infrastructure_msw_to_energy_anaerobic_digesters', 'city')
    op.drop_column('infrastructure_msw_to_energy_anaerobic_digesters', 'county')
    op.add_column('infrastructure_msw_to_energy_anaerobic_digesters',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_msw_to_energy_anaerobic_digesters',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_msw_to_energy_anaerobic_digesters',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_saf_and_renewable_diesel_plants --
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'address')
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'city')
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'state')
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'country')
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_wastewater_treatment_plants --
    op.drop_column('infrastructure_wastewater_treatment_plants', 'city')
    op.drop_column('infrastructure_wastewater_treatment_plants', 'county')
    op.drop_column('infrastructure_wastewater_treatment_plants', 'state')
    op.drop_column('infrastructure_wastewater_treatment_plants', 'zipcode')
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infrastructure_petroleum_pipelines')
    op.drop_table('multilinestring')
    op.alter_column('infrastructure_biodiesel_plants', 'address',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('infrastructure_biodiesel_plants', 'updated_at')
    op.drop_column('infrastructure_biodiesel_plants', 'created_at')
    # ### end Alembic commands ###

    # -------------------------------------------------------------------------
    # Reverse infrastructure address normalization
    # -------------------------------------------------------------------------

    # -- infrastructure_biosolids_facilities --
    op.drop_column('infrastructure_biosolids_facilities', 'address_id')
    op.drop_column('infrastructure_biosolids_facilities', 'created_at')
    op.drop_column('infrastructure_biosolids_facilities', 'updated_at')
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('facility_address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('facility_city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('facility_zip', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('facility_county', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('mailing_street_1', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('mailing_city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('mailing_state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('mailing_zip', sa.VARCHAR(), nullable=True))

    # -- infrastructure_cafo_manure_locations --
    op.drop_column('infrastructure_cafo_manure_locations', 'address_id')
    op.drop_column('infrastructure_cafo_manure_locations', 'created_at')
    op.drop_column('infrastructure_cafo_manure_locations', 'updated_at')
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('town', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('zip', sa.VARCHAR(), nullable=True))

    # -- infrastructure_combustion_plants --
    op.drop_column('infrastructure_combustion_plants', 'address_id')
    op.drop_column('infrastructure_combustion_plants', 'created_at')
    op.drop_column('infrastructure_combustion_plants', 'updated_at')
    op.add_column('infrastructure_combustion_plants',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_combustion_plants',
                  sa.Column('county', sa.VARCHAR(), nullable=True))

    # -- infrastructure_district_energy_systems --
    op.drop_column('infrastructure_district_energy_systems', 'address_id')
    op.drop_column('infrastructure_district_energy_systems', 'created_at')
    op.drop_column('infrastructure_district_energy_systems', 'updated_at')
    op.add_column('infrastructure_district_energy_systems',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_district_energy_systems',
                  sa.Column('state', sa.VARCHAR(), nullable=True))

    # -- infrastructure_ethanol_biorefineries --
    op.drop_column('infrastructure_ethanol_biorefineries', 'address_id')
    op.drop_column('infrastructure_ethanol_biorefineries', 'created_at')
    op.drop_column('infrastructure_ethanol_biorefineries', 'updated_at')
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('state', sa.VARCHAR(), nullable=True))

    # -- infrastructure_food_processing_facilities --
    op.drop_column('infrastructure_food_processing_facilities', 'address_id')
    op.drop_column('infrastructure_food_processing_facilities', 'created_at')
    op.drop_column('infrastructure_food_processing_facilities', 'updated_at')
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('county', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('state', sa.VARCHAR(), nullable=True))

    # -- infrastructure_landfills --
    op.drop_column('infrastructure_landfills', 'address_id')
    op.drop_column('infrastructure_landfills', 'created_at')
    op.drop_column('infrastructure_landfills', 'updated_at')
    op.add_column('infrastructure_landfills',
                  sa.Column('physical_address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('county', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('zip_code', sa.VARCHAR(), nullable=True))

    # -- infrastructure_livestock_anaerobic_digesters --
    op.drop_column('infrastructure_livestock_anaerobic_digesters', 'address_id')
    op.drop_column('infrastructure_livestock_anaerobic_digesters', 'created_at')
    op.drop_column('infrastructure_livestock_anaerobic_digesters', 'updated_at')
    op.add_column('infrastructure_livestock_anaerobic_digesters',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_livestock_anaerobic_digesters',
                  sa.Column('state', sa.VARCHAR(), nullable=True))

    # -- infrastructure_msw_to_energy_anaerobic_digesters --
    op.drop_column('infrastructure_msw_to_energy_anaerobic_digesters', 'address_id')
    op.drop_column('infrastructure_msw_to_energy_anaerobic_digesters', 'created_at')
    op.drop_column('infrastructure_msw_to_energy_anaerobic_digesters', 'updated_at')
    op.add_column('infrastructure_msw_to_energy_anaerobic_digesters',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_msw_to_energy_anaerobic_digesters',
                  sa.Column('county', sa.VARCHAR(), nullable=True))

    # -- infrastructure_saf_and_renewable_diesel_plants --
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'address_id')
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'created_at')
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'updated_at')
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('country', sa.VARCHAR(), nullable=True))

    # -- infrastructure_wastewater_treatment_plants --
    op.drop_column('infrastructure_wastewater_treatment_plants', 'address_id')
    op.drop_column('infrastructure_wastewater_treatment_plants', 'created_at')
    op.drop_column('infrastructure_wastewater_treatment_plants', 'updated_at')
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('county', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('zipcode', sa.VARCHAR(), nullable=True))
